### ISSUE TITLE
Pseudoknot is not an argument. 

### ISSUE THREAD

**Issue by dirkweissenborn** [DasLab/arnie#15]
https://github.com/DasLab/arnie/blob/702f70bb56b20d49c9aa411cb6d537f9e4e60517/pfunc.py#L59

**Comment by ratthachat** [comment]
While the PR is not accepted yet, we can simply changes variable name 

https://github.com/DasLab/arnie/pull/12

**Comment by rkretsch** [comment]
I believe this has been addressed so closing issue.
https://github.com/DasLab/arnie/blob/64b0ff33361cc18c6382db6443f8e576bf4d212c/pfunc.py#L59
