### ISSUE TITLE
Correct link to RNAsoft?

### ISSUE THREAD

**Issue by mandar5335** [DasLab/arnie#16]
Hi,
I am trying to get multiRNAfold tarball with the link: http://www.rnasoft.ca/download.html

However, the link directs to some random webpage? 

Is there any updated link for RNAsoft? 

Best,
Mandar Kulkarni

**Comment by HWaymentSteele** [comment]
Hi, I'm afraid I also can no longer find any links to RNAsoft, I will update the text in the documentation!
