### ISSUE TITLE
argument 'pseudo' should be 'pseudoknots'?

### ISSUE THREAD

**Issue by juvion** [DasLab/arnie#17]
https://github.com/DasLab/arnie/blob/19e9cbaf6d5ade5891affd28f1311716168a0506/free_energy.py#L47

``` {python}
free_energy('GGGUUUCCC',package='vienna')
Traceback (most recent call last):
....
    return pfunc(seq, package=package, T=T, dangles=dangles, coaxial=coaxial, pseudo=pseudo, dna=dna, beam_size = beam_size,
TypeError: pfunc() got an unexpected keyword argument 'pseudo'
```

**Comment by rkretsch** [comment]
I believe this has been addressed as pfunc now accepts the argument 'pseudo'. Closing issue.
https://github.com/DasLab/arnie/blob/64b0ff33361cc18c6382db6443f8e576bf4d212c/pfunc.py#L13
