### ISSUE TITLE
Arnie without eternafold key

### ISSUE THREAD

**Issue by JackMaguire** [DasLab/arnie#3]
Hello, I am trying to use Arnie without eternafold installed. I find that my system crashes unless I change

```py
    if 'eternafoldparams' not in return_dct.keys():                                         
      return_dct['eternafoldparams'] = "%s/../params/EternaFoldParams.v1" % return_dct['eternafold']
```

to

```py
    if 'eternafoldparams' not in return_dct.keys() and 'eternafold' in return_dct.keys():                                         
      return_dct['eternafoldparams'] = "%s/../params/EternaFoldParams.v1" % return_dct['eternafold']
```

at the end of `utils.py` because my dict doesn't have the `'eternafold '` key. Figured I'd post this here as a suggestion but maybe I'm just using Arnie incorrectly

**Comment by HWaymentSteele** [comment]
Thanks so much for catching that Jack! Implemented the change.
