### ISSUE TITLE
structure string with unbalanced brace brackets returned from rnss

### ISSUE THREAD

**Issue by jandersonlee** [DasLab/arnie#48]
The following routine appears to be returning a secondary structure with unbalanced brace brackets on rare occasions:

def rnss(model,sequence):
    """fold a seqeunce; return shp,bp"""
    #print(model,sequence)
    if isinstance(sequence,str):
        # pre-condition text sequences for processing
        tokens={nt:i for i,nt in enumerate('ACGU')}
        sequence=[tokens[nt] for nt in sequence]
        sequence=np.array(sequence)
        sequence=torch.tensor(sequence)
    sequence=sequence.cuda().unsqueeze(0)
    with torch.no_grad():
        preds = model(sequence).sigmoid().cpu().numpy()
    #print(repr(preds[0]))
    shp,bp=_hungarian(preds[0],theta=0.7) #best theta based on val is 0.7
    #ct_matrix=np.zeros((len(s),len(s)))
    #for b in bp:
    #    ct_matrix[b[0],b[1]]=1
    #ct_matrix=ct_matrix+ct_matrix.T
    return shp,preds[0]

I believe the code I am working with was originally called rnss.py from a directory called ribonet. The error traces shown below from my code list the sequence and the returned secondary structure that has unbalanced brace brckets. It has 4 '{' but 6 '}'.

It is probably in the call to _hungarian that the error is occuring.

It is only later when I try to parse the shape string to determine the pairing that the problem shows up.

The version of hungarian.py that I am using is very old. I don't know if it has been updated:

-rw-r--r-- 1 jandlee rhiju     2079 Feb 16  2024 hungarian.py

The copy of the directory that I am working on is also not set up as a git repo, so I cannot pull updates:

[jandlee@sh04-ln02 login ~/grp/ribonet]$ git status
fatal: Not a git repository (or any parent up to mount point /home/groups/rhiju)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

This is not the only sequence that it failed on, but it is the only one I have recovered so far.

Rhiju suggested that I open a ticket here.

 Jeff Andersonlee
jandersonlee@gmail.com

OOPS: MEF2C-AS1:49 1945-2183,UAAAAAUAUCUUUUUGUGUCUCUUUAGAUAUCUCUUAAUGCACUCUAGGUGUCAAAUAUGAGCAAUCUGUUUGUAGGAGAGAAUGGCUCCUUGCUCCAAUAGGUAGAUC
UCUCUAAGAAUCCUCCUAACACACUAUUGUUAACUUAUAAAUAUGCUCAGGCACAUAAUAGGUACUUAGUAAAUAUAUGUUGACUCUUGAAUGAAGAGCUGAUUGGAGUAAUGAAAACAGCCUGUGUUAGA,MEF2C-
AS1:49 1945-2183
Traceback (most recent call last):
  File "/home/groups/rhiju/jandlee/ribonet/bpc.py", line 67, in shape2match0
    elif (c=='}'): update(bb,i,m)
  File "/home/groups/rhiju/jandlee/ribonet/bpc.py", line 49, in update
    n=stk.pop()
IndexError: pop from empty list
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/groups/rhiju/jandlee/ribonet/rnh.py", line 214, in main
    cpcnf = bppConfidence(shp,bpp)
  File "/home/groups/rhiju/jandlee/ribonet/bpc.py", line 101, in bppConfidence
    m0 = shape2match0(shp)
  File "/home/groups/rhiju/jandlee/ribonet/bpc.py", line 75, in shape2match0
    raise ValueError('shape2match0: bad shape:', shp)
ValueError: ('shape2match0: bad shape:', '.....((((((......[[[.....))))))........((((.....))))((.................<)...........((((..((((((
((((........................{>{{{{............................]]]...............................(((((.....)))))...)))))))))).......))))..}
}}}}}.')

**Comment by luxaritas** [comment]
It may well be that you're using older copies of arnie-derived code which has issues. I would recommend replacing the definition of `_hungarian` with [the current version](https://github.com/DasLab/arnie/blob/2133d5c175c78563ad1529e698c19f3b2b2f03e5/src/arnie/pk_predictors.py#L108) as well as replacing the content of `arnie_utils.py` (which I happen to know exists in the code you're working with) with [the current version of utils.py](https://github.com/DasLab/arnie/blob/2133d5c175c78563ad1529e698c19f3b2b2f03e5/src/arnie/utils.py)

**Comment by jandersonlee** [comment]
Changing to the newer arnie code for _hungarian appears to have fixed it.
It still feels like my ribonet code for Rnet-SS is bandaged together, but
it's working for now. Thanks.

Jeff

**Comment by luxaritas** [comment]
Unfortunately that's somewhat the nature of RNet-SS. https://github.com/Shujun-He/RibonanzaNet is the canonical repository for the foundation model, but the secondary structure code is only available via the kaggle notebook.

Glad you were able to get it resolved!
