### ISSUE TITLE
which version of python?

### ISSUE THREAD

**Issue by candress** [DasLab/arnie#7]
Hello, I am struggling to get this program to work. Can you tell me:
1. does this work with python 2.7 or only python 3?
2. am I able to use this package outside of my working directory?
3. I am trying to use mfe with ONLY EternaFold installed. I am receiving an error as it's trying to use vienna. Is this not possible?
I followed the setup instructions "You don't have to install all of the packages described here for Arnie to work. Your needs will dictate what other packages you set up."

**Comment by HWaymentSteele** [comment]
Hi candress,

1. Arnie has been tested with python 3.

2. You can point python to this directory by adding to your python path: 
Add to your .bashrc: 

export PYTHONPATH=$PYTHONPATH:/path/to/arnie

This is in the readme, I have added the above to the setup_doc.md as well.

3. Does mfe work if you run `mfe(seq, package='eternafold')`? This will of course need the rest of your setup to work.

Hope this helps!

**Comment by candress** [comment]
1. Thank you! good to know.
2. I have done so and it doesn't seem to be working for me (not entirely sure why, might be because I am using 1 of many profiles). Am I just pointing to the folder "arnie" or is there an executable I should be pointing to? (my apologies if this is common knowledge, I am new to linux)
3. I receive an error:
$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arnie
>>> from arnie.mfe import mfe
>>> import arnie.utils as utils
>>> utils.package_list()
['eternafold']
>>> sequence = "CGCUGUCUGUACUUGUAUCAGUACACUGACGAGUCCCUAAAGGACGAAACAGCG"
>>> mfe_structure = mfe(sequence,package='eternafold')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/student4/arnie/mfe.py", line 109, in mfe
    return struct
UnboundLocalError: local variable 'struct' referenced before assignment

it seems that the mfe script is skipping past the elif pkg=='eternafold' and jumping right to "if return_dG_MFE: return struct, even though I have eternafold installed (I successfully tested it)

here is what my arnie.txt file looks like:
#paths to local installations of packages.  If package is not installed, leave as None
#Replace paths below with paths to your installations.
#NB: .gitignore file ignores *.arnie files. Name it as such if you don't want your local path file 
#included with your git repo.

#Path to EternaFold
eternafold: /home/EternaFold/src

#TMP: location for tmp files for packages. Update to where you want your tmp files stored.
TMP: /home/student4/tmp


and here are my bash rc exports:
export ARNIEFILE=/home/student4/arnie/arnie.txt
export PYTHONPATH=$PYTHONPATH:/home/student4/arnie

**Comment by candress** [comment]
Is this issue still being addressed? It isn't solved yet.

**Comment by everyday847** [comment]
There's no way for a script to skip a line like that `elif`. It seems more likely that the `mfe_contrafold_` call is crashing or something. Are you sure that's the accurate path to eternafold? It looks a little unusual because it seems like the rest of your software is installed in `/home/student4/` but your eternafold path reads `/home/EternaFold/`.

Re: (2), yes, you add the `arnie` folder to your $PYTHONPATH; there is no executable. We may not be very much use debugging your environment setup remotely, but there are lots of resources teaching you how to set your $PYTHONPATH online.

**Comment by candress** [comment]
Thank you for the reply. I will look into this further and get back to you.
