### ISSUE TITLE
Segmentation fault running linear partition

### ISSUE THREAD

**Issue by dirkweissenborn** [DasLab/arnie#8]
Hi!
I am trying to run linear partition from arnie and it fails with segmentation fault running the following code, for instance.
```
In [5]: pfunc.pfunc_linearpartition_('AAAAAAAAA', package='vienna')
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-5-fa89ff9f43a7> in <module>
----> 1 pfunc.pfunc_linearpartition_('AAAAAAAAA', package='vienna')

/app/arnie/arnie/pfunc.py in pfunc_linearpartition_(seq, bpps, package, beam_size, return_free_energy, DEBUG)
    551 
    552     if p.returncode:
--> 553         raise Exception('LinearPartition failed: on %s\n%s' % (seq, stderr))
    554 
    555     os.remove("%s.sh" % tmp_command)

Exception: LinearPartition failed: on AAAAAAAAA
b'Segmentation fault (core dumped)\n'
```

I installed LinearPartition and ViennaRNA as described in the  setup  docs.

LinearPartition seems to work from the command line, so i suspect that something within ARNIE is not working properly?
```
$ echo GGGCUCGUAGAUCAGCGGUAGAUCGCUUCCUUCGCAAGGAAGCCCUGGGUUCAAAUCCCAGCGAGUCCACCA | ./linearpartition -o output2
Log Partition Coefficient: 15.88272
Outputing base pairing probability matrix to output2...
Done!
```

I am running on Debian10 inside docker.

**Comment by dirkweissenborn** [comment]
Ok, so I got it to work with 2 minor changes:

1) When creating the call cmd for linearpartition I had to change the empty argument from `'_'` to `"''"`.
2) linearpartition accepts 16 arguments but only 15 were given, so I added an additional empty arg to the list. Not sure why this is, maybe linearpartition got an update?

Can you confirm this?

**Comment by HWaymentSteele** [comment]
Hi Dirk! Sorry about this. That's exactly right. I just merged a PR/ updated it to match with your above change.

The reason this happens is because new versions of linearpartition continue to add to the command line args and make our old wrapper outdated.  A better wrapper would call the python wrapper in linearpartition itself 🙃

**Comment by dirkweissenborn** [comment]
I think this is not quite fixed yet :)
